<?php

namespace fichatecnica\fichaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * bienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bienRepository extends EntityRepository
{
}
