<?php

namespace fichatecnica\fichaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * dependenciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dependenciasRepository extends EntityRepository
{
}
