<?php

namespace fichatecnica\fichaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tipocomponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipocomponenteRepository extends EntityRepository
{
}
