<?php

namespace fichatecnica\fichaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tipobienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipobienRepository extends EntityRepository
{
}
