parameters:
#    ficha.example.class: fichatecnica\fichaBundle\Example

services:
#    ficha.example:
#        class: %ficha.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
